[build]
  command = "npm run build"
  base = "."
  publish = "build"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 8080
  publish = "build"
  autoLaunch = true
  framework = "#custom"